module.exports = {
  preset: 'react-native',
  moduleDirectories: ['node_modules', 'src'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@domain/(.*)$': '<rootDir>/src/domain/$1',
    '^@infrastructure/(.*)$': '<rootDir>/src/infrastructure/$1',
    '^@application/(.*)$': '<rootDir>/src/application/$1',
    '^@screens/(.*)$': '<rootDir>/src/screens/$1',
    '^@presentation/(.*)$': '<rootDir>/src/presentation/$1',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?@?react-native|@react-native-community|@react-navigation|@reduxjs|immer|@shopify|@ai-sdk|ai)',
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/__tests__/helpers/',
    '/__tests__/setup\\.ts$',
    '/__tests__/fixtures/',
    '/__tests__/builders/',
    '/__tests__/mocks/',
    '/docs/ignored/',
  ],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup.ts'],
  testEnvironment: 'node',
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/**/specs/**',
    '!src/**/*.stories.{ts,tsx}',
    '!src/svg-icons/**',
    '!src/assets/**',
    '!src/**/index.ts',
    '!src/ReactotronConfig.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 13,
      functions: 15,
      lines: 15,
      statements: 15,
    },
  },
  coverageReporters: ['text', 'text-summary', 'lcov', 'json-summary'],
  coverageDirectory: 'coverage',
};
